export const riskAgent = {
    id: 'risk',
    name: 'Risco',
    description: 'Gestão de risco de uma gestora brasileira: risco de mercado (VaR, CVaR, stress, sensibilidades), ' +
        'risco de crédito e contraparte, risco de liquidez, margem e garantias na B3, ' +
        'enquadramento de mandato e limites regulatórios (CVM, ANBIMA) e monitoramento de alertas.',
};
export const riskCommands = [
    {
        id: 'risk.calcular_var',
        agent: 'risk',
        name: 'Calcular VaR da carteira',
        description: 'Calcula a perda potencial da carteira (VaR e CVaR/expected shortfall) para um horizonte e nível de confiança; use quando pedirem a métrica de risco de mercado em si, não a validação do modelo nem um cenário específico.',
        utterances: [
            'me dá o VaR da carteira',
            'quanto posso perder num dia ruim com 99% de confiança?',
            'VaR paramétrico e histórico do fundo',
            'CVaR 97,5',
            'roda o value at risk do book de renda variável',
            'qual a perda esperada na cauda da distribuição?',
            'calcula o VaR de 252 dias pro consolidado da gestora',
            'compute portfolio VaR at 99% over a ten day horizon',
            "what's our expected shortfall right now?",
            'daily value at risk report',
            'calcula el VaR de la cartera',
            '¿cuál es la pérdida esperada en la cola al 99%?',
        ],
        keywords: ['VaR', 'CVaR', 'value at risk', 'expected shortfall', 'PnL', 'Monte Carlo', 'PL', 'percentil 99'],
        params: [
            {
                name: 'carteira',
                type: 'string',
                required: true,
                description: 'Identificador do fundo, book ou carteira consolidada a ser avaliada.',
            },
            {
                name: 'metodo',
                type: 'enum',
                required: false,
                description: 'Metodologia de cálculo do VaR.',
                enumValues: ['historico', 'parametrico', 'monte_carlo'],
            },
            {
                name: 'confianca',
                type: 'enum',
                required: false,
                description: 'Nível de confiança estatístico do cálculo.',
                enumValues: ['90', '95', '97.5', '99', '99.9'],
            },
            {
                name: 'horizonte',
                type: 'enum',
                required: false,
                description: 'Horizonte de manutenção da posição usado no cálculo.',
                enumValues: ['1d', '5d', '10d', '21d'],
            },
            {
                name: 'incluirCvar',
                type: 'boolean',
                required: false,
                description: 'Se verdadeiro, retorna também o CVaR (expected shortfall) além do VaR.',
            },
        ],
        confusableWith: ['risk.backtest_var', 'risk.stress_test', 'risk.sensibilidade_taxa'],
    },
    {
        id: 'risk.stress_test',
        agent: 'risk',
        name: 'Rodar stress test',
        description: 'Reprecifica a carteira sob um cenário de choque hipotético ou histórico (câmbio, curva de juros, bolsa) e mostra o impacto; use quando o pedido descrever um "e se" ou um cenário nomeado.',
        utterances: [
            'roda um stress aí',
            'simula o dólar a 7 reais na carteira',
            'aplica o cenário de 2008 no book',
            'stress test com choque de 300 bps na curva pré',
            'e se a bolsa cair 20%?',
            'quanto o fundo perde num cenário de crise cambial?',
            'cenário de estresse ANBIMA nos ativos ilíquidos',
            'run a stress scenario on the portfolio',
            'what if rates spike 300bps tomorrow?',
            'shock the book with a 2008 style crash',
            'corre un stress test con una caída del 20% en bolsa',
            'simula un escenario de crisis cambiaria en la cartera',
        ],
        keywords: ['stress test', 'cenário', 'choque', 'bps', 'ANBIMA', 'crash', 'what-if', 'reprecificação'],
        params: [
            {
                name: 'carteira',
                type: 'string',
                required: true,
                description: 'Fundo ou book que receberá o choque.',
            },
            {
                name: 'cenario',
                type: 'enum',
                required: true,
                description: 'Cenário de estresse a ser aplicado.',
                enumValues: ['crise_2008', 'covid_2020', 'joesley_2017', 'alta_juros', 'choque_cambial', 'customizado'],
            },
            {
                name: 'fatorChoque',
                type: 'number',
                required: false,
                description: 'Magnitude do choque quando o cenário é customizado (em % ou bps, conforme o fator).',
            },
            {
                name: 'reversao',
                type: 'boolean',
                required: false,
                description: 'Se verdadeiro, executa também o cenário reverso (choque de sinal invertido).',
            },
        ],
        confusableWith: ['risk.calcular_var', 'risk.sensibilidade_taxa'],
    },
    {
        id: 'risk.checar_enquadramento',
        agent: 'risk',
        name: 'Checar enquadramento de limites',
        description: 'Verifica se a carteira atual (ou uma ordem antes de executar) respeita os limites do mandato, do regulamento e da regulação; use para conferência de conformidade, não para listar alertas já disparados.',
        utterances: [
            'checa o enquadramento do fundo',
            'tô dentro do mandato?',
            'a carteira respeita o regulamento?',
            'verifica o limite de 20% por emissor',
            'enquadramento CVM 175 e política de investimento',
            'posso comprar mais VALE3 sem furar o limite de renda variável?',
            'compliance de mandato pré-trade',
            'check the portfolio against its mandate limits',
            'are we within the investment policy constraints?',
            'pre-trade limit check for this order',
            'verifica el cumplimiento de los límites del mandato',
            '¿la cartera está dentro de la política de inversión?',
        ],
        keywords: ['enquadramento', 'mandato', 'CVM 175', 'RCVM 175', 'ANBIMA', 'política de investimento', 'pré-trade', 'vedações'],
        params: [
            {
                name: 'carteira',
                type: 'string',
                required: true,
                description: 'Fundo ou carteira cujo enquadramento será verificado.',
            },
            {
                name: 'momento',
                type: 'enum',
                required: false,
                description: 'Se a checagem é sobre a posição atual ou simulando uma ordem ainda não executada.',
                enumValues: ['pre_trade', 'pos_trade'],
            },
            {
                name: 'ordemSimulada',
                type: 'string',
                required: false,
                description: 'Ordem hipotética a incluir na checagem, no formato "ativo quantidade lado".',
            },
            {
                name: 'escopo',
                type: 'enum',
                required: false,
                description: 'Conjunto de regras a aplicar na verificação.',
                enumValues: ['regulatorio', 'mandato', 'interno', 'todos'],
            },
        ],
        confusableWith: ['risk.alertas_limite', 'risk.concentracao'],
    },
    {
        id: 'risk.exposicao_por_fator',
        agent: 'risk',
        name: 'Abrir exposição por fator',
        description: 'Decompõe a exposição comprada e vendida da carteira por fator de risco, setor, país ou moeda, com beta agregado; use para entender de onde vem o risco, não o quanto ele é concentrado em poucos nomes.',
        utterances: [
            'abre a exposição por setor',
            'quanto eu tenho de exposição em dólar?',
            'quebra a carteira por fator de risco',
            'net e gross exposure por país',
            'exposição a commodities',
            'qual o beta agregado da carteira contra o Ibovespa?',
            'me mostra o direcional em juros, bolsa e câmbio separado',
            'break down exposure by sector and factor',
            'show me net versus gross exposure of the fund',
            'currency exposure breakdown please',
            'desglosa la exposición por sector',
            '¿cuánta exposición tenemos en dólares?',
        ],
        keywords: ['exposição', 'net exposure', 'gross exposure', 'beta', 'Ibovespa', 'IBOV', 'USD', 'fator de risco', 'setorial'],
        params: [
            {
                name: 'carteira',
                type: 'string',
                required: true,
                description: 'Fundo ou book a decompor.',
            },
            {
                name: 'dimensao',
                type: 'enum',
                required: true,
                description: 'Eixo pelo qual a exposição será agrupada.',
                enumValues: ['fator', 'setor', 'moeda', 'pais', 'classe_de_ativo'],
            },
            {
                name: 'base',
                type: 'enum',
                required: false,
                description: 'Se a exposição é reportada em valor nocional ou ajustada por beta.',
                enumValues: ['nocional', 'beta_ajustada'],
            },
        ],
        confusableWith: ['risk.concentracao', 'risk.tracking_error'],
    },
    {
        id: 'risk.tracking_error',
        agent: 'risk',
        name: 'Medir tracking error',
        description: 'Calcula o risco ativo da carteira contra um benchmark — tracking error anualizado, information ratio e desvios ativos por posição; use quando a referência for um índice, não risco absoluto.',
        utterances: [
            'qual o tracking error contra o CDI?',
            'TE anualizado do fundo',
            'o quanto eu tô descolando do benchmark?',
            'erro de rastreamento versus Ibovespa nos últimos 12 meses',
            'calcula o information ratio junto com o risco ativo',
            'quais posições mais contribuem pro desvio contra o índice?',
            'risco ativo do indexado',
            "what's the tracking error against the benchmark?",
            'active risk versus the index over one year',
            'compute the information ratio for this fund',
            'calcula el tracking error contra el índice',
            '¿cuánto nos desviamos del benchmark este año?',
        ],
        keywords: ['tracking error', 'TE', 'information ratio', 'IR', 'benchmark', 'CDI', 'IBOV', 'IMA-B', 'risco ativo'],
        params: [
            {
                name: 'carteira',
                type: 'string',
                required: true,
                description: 'Fundo ou carteira a comparar com o benchmark.',
            },
            {
                name: 'benchmark',
                type: 'enum',
                required: true,
                description: 'Índice de referência usado como comparação.',
                enumValues: ['CDI', 'IBOV', 'IBRX', 'IMA-B', 'IMA-B5', 'IHFA', 'SP500'],
            },
            {
                name: 'janela',
                type: 'enum',
                required: false,
                description: 'Janela histórica de retornos usada no cálculo.',
                enumValues: ['3m', '6m', '12m', '24m', '36m'],
            },
            {
                name: 'contribuicaoPorAtivo',
                type: 'boolean',
                required: false,
                description: 'Se verdadeiro, abre a contribuição de cada posição para o tracking error.',
            },
        ],
        confusableWith: ['risk.exposicao_por_fator', 'risk.calcular_var'],
    },
    {
        id: 'risk.concentracao',
        agent: 'risk',
        name: 'Analisar concentração',
        description: 'Mede o quanto o risco está acumulado em poucos nomes, emissores ou grupos econômicos, com HHI e peso das maiores posições; use quando a pergunta for sobre "estar concentrado", não sobre a composição por setor.',
        utterances: [
            'risco de concentração da carteira',
            'quanto pesa a maior posição?',
            'as top 10 posições concentram quanto do PL?',
            'HHI do book',
            'tem algum emissor com mais de 10% do patrimônio?',
            'concentração por grupo econômico e por emissor',
            'a gente tá muito concentrado em bancos?',
            'concentration risk report for the fund',
            'how much do the top five holdings represent?',
            'Herfindahl index of the portfolio',
            'análisis de concentración por emisor',
            '¿cuál es el peso de la mayor posición de la cartera?',
        ],
        keywords: ['concentração', 'HHI', 'Herfindahl', 'top 10', 'emissor', 'grupo econômico', 'PL', 'diversificação'],
        params: [
            {
                name: 'carteira',
                type: 'string',
                required: true,
                description: 'Fundo ou book a analisar.',
            },
            {
                name: 'agrupamento',
                type: 'enum',
                required: false,
                description: 'Nível em que as posições são somadas antes de medir a concentração.',
                enumValues: ['ativo', 'emissor', 'grupo_economico', 'setor'],
            },
            {
                name: 'topN',
                type: 'number',
                required: false,
                description: 'Quantidade de maiores posições a detalhar no resultado.',
            },
        ],
        confusableWith: ['risk.exposicao_por_fator', 'risk.checar_enquadramento'],
    },
    {
        id: 'risk.liquidez_carteira',
        agent: 'risk',
        name: 'Avaliar risco de liquidez',
        description: 'Estima em quantos dias a carteira seria liquidada dado um limite de participação no volume negociado e confronta isso com o passivo de resgates; use para prazo de saída e capacidade de honrar resgates.',
        utterances: [
            'em quantos dias eu zero essa posição?',
            'risco de liquidez da carteira',
            'quanto tempo pra liquidar 100% do book?',
            'dias pra sair de PETR4 sem passar de 20% do ADTV',
            'liquidez em D+1',
            'consigo honrar os resgates dessa semana?',
            'que fatia da carteira é liquidável em até 5 dias?',
            'days to liquidate the portfolio at 20% of ADTV',
            'liquidity risk under a redemption stress scenario',
            'how long would it take to unwind this position?',
            '¿en cuántos días puedo liquidar la cartera?',
            'riesgo de liquidez frente a los rescates',
        ],
        keywords: ['liquidez', 'ADTV', 'dias para liquidar', 'resgate', 'D+1', 'D+30', 'giro', 'passivo', 'cotização'],
        params: [
            {
                name: 'carteira',
                type: 'string',
                required: true,
                description: 'Fundo ou book cuja liquidez será estimada.',
            },
            {
                name: 'participacaoVolume',
                type: 'number',
                required: false,
                description: 'Percentual máximo do volume diário médio que se assume consumir por dia.',
            },
            {
                name: 'cenarioResgate',
                type: 'enum',
                required: false,
                description: 'Intensidade do resgate simulado contra a liquidez dos ativos.',
                enumValues: ['normal', 'estresse_moderado', 'estresse_severo'],
            },
            {
                name: 'ativo',
                type: 'string',
                required: false,
                description: 'Restringe a análise a um único ativo ou ticker.',
            },
        ],
        confusableWith: ['risk.margem_garantias', 'risk.concentracao'],
    },
    {
        id: 'risk.margem_garantias',
        agent: 'risk',
        name: 'Consultar margem e garantias',
        description: 'Apura a margem exigida pela câmara nos derivativos, as garantias depositadas e se há chamada de margem em aberto; use para colateral e caixa de garantia, não para prazo de liquidação de ativos.',
        utterances: [
            'quanto de margem a B3 tá exigindo?',
            'tem chamada de margem hoje?',
            'margem requerida CORE dos derivativos',
            'quanto de garantia eu preciso depositar?',
            'call de margem',
            'sobra caixa livre depois da margem?',
            'calcula a margem exigida se eu dobrar a posição em DI futuro',
            "what's our margin requirement at the clearing house today?",
            'any pending margin call on the derivatives book?',
            'collateral posted versus collateral required',
            '¿cuánto margen exige la cámara de compensación?',
            '¿hay llamada de margen pendiente para hoy?',
        ],
        keywords: ['margem', 'CORE', 'B3', 'chamada de margem', 'margin call', 'garantias', 'colateral', 'clearing', 'DI futuro'],
        params: [
            {
                name: 'carteira',
                type: 'string',
                required: true,
                description: 'Fundo ou book com posições em derivativos.',
            },
            {
                name: 'camara',
                type: 'enum',
                required: false,
                description: 'Câmara de compensação de referência.',
                enumValues: ['B3', 'CME', 'LCH', 'todas'],
            },
            {
                name: 'simularPosicao',
                type: 'string',
                required: false,
                description: 'Posição hipotética adicional para recalcular a margem, no formato "contrato quantidade".',
            },
        ],
        confusableWith: ['risk.liquidez_carteira', 'risk.sensibilidade_taxa'],
    },
    {
        id: 'risk.sensibilidade_taxa',
        agent: 'risk',
        name: 'Calcular sensibilidades',
        description: 'Retorna as sensibilidades analíticas das posições — DV01 por vértice, duration, convexidade e gregas de opções; use quando pedirem a derivada do preço a um fator, não uma perda simulada.',
        utterances: [
            'qual o DV01 do book de juros?',
            'duration modificada da carteira de crédito',
            'me passa as gregas das opções',
            'delta e vega da estrutura em PETR4',
            'quanto eu perco se a curva subir 1 bp?',
            'DV01 por vértice',
            'convexidade da posição em NTN-B',
            'show DV01 broken down by curve bucket',
            'option greeks for the whole book',
            'modified duration of the bond portfolio',
            '¿cuál es el DV01 de la cartera de tasas?',
            'muéstrame las griegas de las opciones',
        ],
        keywords: ['DV01', 'PV01', 'duration', 'convexidade', 'delta', 'gamma', 'vega', 'theta', 'NTN-B', 'bps'],
        params: [
            {
                name: 'carteira',
                type: 'string',
                required: true,
                description: 'Book ou carteira cujas sensibilidades serão calculadas.',
            },
            {
                name: 'metrica',
                type: 'enum',
                required: true,
                description: 'Sensibilidade desejada.',
                enumValues: ['dv01', 'duration', 'convexidade', 'delta', 'gamma', 'vega', 'theta'],
            },
            {
                name: 'curva',
                type: 'enum',
                required: false,
                description: 'Curva de referência quando a métrica é de juros.',
                enumValues: ['pre', 'ipca', 'cupom_cambial', 'sofr'],
            },
            {
                name: 'porVertice',
                type: 'boolean',
                required: false,
                description: 'Se verdadeiro, abre o resultado vértice a vértice em vez de agregado.',
            },
        ],
        confusableWith: ['risk.calcular_var', 'risk.stress_test', 'risk.margem_garantias'],
    },
    {
        id: 'risk.backtest_var',
        agent: 'risk',
        name: 'Backtestar modelo de VaR',
        description: 'Confronta o VaR previsto com o PnL realizado no histórico, conta as exceções e roda os testes de aderência (Kupiec, Christoffersen); use para validar a qualidade do modelo, não para obter o VaR de hoje.',
        utterances: [
            'roda o backtest do modelo de VaR',
            'quantas exceções a gente teve no ano?',
            'o VaR furou quantas vezes?',
            'teste de Kupiec do modelo de risco',
            'validação do modelo pro relatório do regulador',
            'backtesting VaR 250 dias',
            'o modelo tá calibrado ou tá subestimando o risco?',
            'backtest the VaR model over the last year',
            'how many VaR exceptions did we have?',
            'run Kupiec and Christoffersen coverage tests',
            'haz el backtesting del modelo de VaR',
            '¿cuántas excepciones tuvo el VaR el año pasado?',
        ],
        keywords: ['backtesting', 'exceções', 'Kupiec', 'Christoffersen', 'VaR', 'PnL realizado', 'zona amarela', 'Basileia'],
        params: [
            {
                name: 'carteira',
                type: 'string',
                required: true,
                description: 'Fundo ou book cujo modelo será validado.',
            },
            {
                name: 'janela',
                type: 'enum',
                required: false,
                description: 'Quantidade de observações históricas usadas no backtest.',
                enumValues: ['125', '250', '500', '750'],
            },
            {
                name: 'confianca',
                type: 'enum',
                required: false,
                description: 'Nível de confiança do VaR que está sendo testado.',
                enumValues: ['95', '97.5', '99'],
            },
            {
                name: 'teste',
                type: 'enum',
                required: false,
                description: 'Teste estatístico de aderência a executar.',
                enumValues: ['kupiec', 'christoffersen', 'ambos'],
            },
        ],
        confusableWith: ['risk.calcular_var'],
    },
    {
        id: 'risk.risco_contraparte',
        agent: 'risk',
        name: 'Analisar risco de crédito e contraparte',
        description: 'Mostra a exposição por contraparte e emissor com rating, spread, probabilidade de default e CVA, sinalizando rebaixamentos; use para qualidade creditícia de quem está do outro lado, não para limites de carteira.',
        utterances: [
            'qual a exposição na contraparte XP?',
            'rating de crédito dos emissores da carteira',
            'risco de contraparte nos swaps de balcão',
            'algum emissor foi rebaixado esse mês?',
            'probabilidade de default dessa debênture',
            'CVA do book de derivativos',
            'spread de crédito por emissor',
            'counterparty credit exposure report',
            'issuer ratings and recent downgrades',
            "what's our CVA on the swap book?",
            'exposición al riesgo de contraparte por banco',
            '¿qué rating tienen los emisores de la cartera?',
        ],
        keywords: ['contraparte', 'rating', 'CVA', 'probabilidade de default', 'PD', 'spread de crédito', 'debênture', 'CDS', 'S&P', 'Moody’s'],
        params: [
            {
                name: 'carteira',
                type: 'string',
                required: true,
                description: 'Fundo ou book com exposição de crédito a analisar.',
            },
            {
                name: 'contraparte',
                type: 'string',
                required: false,
                description: 'Nome ou CNPJ de uma contraparte específica para filtrar o resultado.',
            },
            {
                name: 'ratingMinimo',
                type: 'enum',
                required: false,
                description: 'Rating mínimo aceitável; expõe as posições abaixo desse corte.',
                enumValues: ['AAA', 'AA', 'A', 'BBB', 'BB', 'B'],
            },
            {
                name: 'incluirCva',
                type: 'boolean',
                required: false,
                description: 'Se verdadeiro, calcula o ajuste de valor de crédito (CVA) das posições de balcão.',
            },
        ],
        confusableWith: ['risk.concentracao', 'risk.checar_enquadramento'],
    },
    {
        id: 'risk.alertas_limite',
        agent: 'risk',
        name: 'Listar alertas de limite',
        description: 'Lista os alertas de risco já disparados e os limites estourados, com severidade, responsável e status de tratamento; use para o histórico e a fila de ocorrências, não para checar conformidade de uma posição agora.',
        utterances: [
            'tem algum limite estourado?',
            'lista os alertas de risco abertos',
            'o que disparou hoje?',
            'quais limites furaram essa semana',
            'alertas pendentes de tratamento',
            'me mostra quem passou do limite de VaR ontem',
            'histórico de estouros do book macro nos últimos 30 dias',
            'list all open risk alerts by severity',
            'which limits were breached today?',
            'show me the breach log for last month',
            'muéstrame las alertas de riesgo abiertas',
            '¿qué límites se excedieron hoy?',
        ],
        keywords: ['alerta', 'breach', 'estouro', 'desenquadramento', 'severidade', 'limite de VaR', 'log', 'ocorrência'],
        params: [
            {
                name: 'periodo',
                type: 'enum',
                required: false,
                description: 'Janela de tempo dos alertas a listar.',
                enumValues: ['hoje', 'ontem', '7d', '30d', 'mes_atual'],
            },
            {
                name: 'severidade',
                type: 'enum',
                required: false,
                description: 'Filtra os alertas por gravidade.',
                enumValues: ['baixa', 'media', 'alta', 'critica'],
            },
            {
                name: 'status',
                type: 'enum',
                required: false,
                description: 'Situação do tratamento do alerta.',
                enumValues: ['aberto', 'em_tratamento', 'resolvido', 'todos'],
            },
            {
                name: 'carteira',
                type: 'string',
                required: false,
                description: 'Restringe os alertas a um fundo ou book específico.',
            },
        ],
        confusableWith: ['risk.checar_enquadramento'],
    },
];
//# sourceMappingURL=risk.js.map