export const traderAgent = {
    id: 'trader',
    name: 'Mesa de Trading',
    description: 'Execução e acompanhamento de ordens numa mesa proprietária brasileira: envio, alteração e cancelamento de ordens na B3 e no exterior, book e profundidade, cotações, posição e PnL intradiário, custo de execução, rolagem de futuros, aluguel de ativos (BTC) e saúde da conectividade de roteamento.',
};
export const traderCommands = [
    {
        id: 'trader.enviar_ordem',
        agent: 'trader',
        name: 'Enviar ordem',
        description: 'Envia uma nova ordem de compra ou venda (limite, mercado, stop ou stop limite) ao mercado; use quando o usuário quer efetivamente boletar e abrir/incrementar posição, não simular nem mexer em ordem já existente.',
        utterances: [
            'compra 10 mil PETR4 a mercado',
            'boleta aí 200 WINFUT na venda',
            'quero mandar uma ordem limitada de VALE3 a 62,30',
            'põe um stop de venda no DOLFUT a 5.180',
            'manda pra bolsa uma compra de 500 ITUB4',
            'ordem de venda, 1.000 MGLU3, limite 9,80',
            'abre posição comprada em BOVA11',
            'send a limit buy order for 200 shares of AAPL',
            'place a market sell on the mini index',
            'submit a stop order at 5180',
            'envía una orden de compra a mercado de VALE3',
            'quiero colocar una orden limitada en el dólar futuro',
        ],
        keywords: ['boleta', 'ordem a mercado', 'ordem limite', 'stop limite', 'WINFUT', 'DOLFUT', 'B3', 'DMA', 'day trade'],
        params: [
            { name: 'ativo', type: 'string', required: true, description: 'Ticker ou contrato a ser negociado, ex.: PETR4, WDOQ26.' },
            { name: 'lado', type: 'enum', required: true, description: 'Direção da ordem.', enumValues: ['compra', 'venda'] },
            {
                name: 'tipoOrdem',
                type: 'enum',
                required: true,
                description: 'Tipo de ordem a ser enviada ao livro.',
                enumValues: ['mercado', 'limite', 'stop', 'stop_limite'],
            },
            { name: 'quantidade', type: 'number', required: true, description: 'Quantidade em ações ou contratos.' },
            { name: 'preco', type: 'number', required: false, description: 'Preço limite ou de disparo; ignorado em ordem a mercado.' },
        ],
        confusableWith: ['trader.simular_ordem', 'trader.cancelar_alterar_ordem', 'trader.zerar_posicao'],
    },
    {
        id: 'trader.cancelar_alterar_ordem',
        agent: 'trader',
        name: 'Cancelar ou alterar ordem',
        description: 'Cancela ou reprecifica uma ordem já enviada e ainda aberta no livro, alterando preço ou quantidade; use somente quando a ordem existe e precisa ser derrubada ou emendada, nunca para criar ordem nova.',
        utterances: [
            'cancela aquela ordem de PETR4 que tá pendente',
            'derruba todas as minhas ordens abertas',
            'muda o preço da ordem de VALE3 para 61,50',
            'aumenta a quantidade daquela boleta de ITUB4 pra 2.000',
            'aciona o kill switch, cancela geral agora',
            'tira aquela oferta do livro, não quero mais',
            'replace da ordem 88213, novo preço 9,70',
            'cancel my open order on the mini dollar',
            'amend the limit price of order 88213',
            'pull all working orders right now',
            'cancela la orden pendiente de VALE3',
            'modifica el precio de mi orden a 61,50',
        ],
        keywords: ['cancelamento', 'ordem pendente', 'ordem aberta', 'kill switch', 'replace', 'order id', 'FIX 35=G', 'B3'],
        params: [
            { name: 'ordemId', type: 'string', required: false, description: 'Identificador da ordem; dispensável quando a ação é cancelar todas.' },
            {
                name: 'acao',
                type: 'enum',
                required: true,
                description: 'O que fazer com a ordem existente.',
                enumValues: ['cancelar', 'cancelar_todas', 'alterar_preco', 'alterar_quantidade'],
            },
            { name: 'novoPreco', type: 'number', required: false, description: 'Novo preço limite, quando a ação for alterar preço.' },
            { name: 'novaQuantidade', type: 'number', required: false, description: 'Nova quantidade remanescente, quando a ação for alterar quantidade.' },
        ],
        confusableWith: ['trader.enviar_ordem', 'trader.zerar_posicao'],
    },
    {
        id: 'trader.consultar_book',
        agent: 'trader',
        name: 'Abrir book de ofertas',
        description: 'Mostra o livro de ofertas com preços e quantidades por nível, spread e liquidez disponível nas pontas; use quando o usuário quer profundidade do book, e não apenas o último preço negociado.',
        utterances: [
            'abre o book do WDOFUT',
            'como tá a profundidade de PETR4?',
            'quantos lotes tem na primeira ponta de compra do WIN?',
            'me mostra as cinco melhores ofertas de compra e venda de VALE3',
            'spread do livro de MGLU3',
            'tem liquidez pra passar 2 mil contratos sem varrer as pontas?',
            'agrupa o book do dólar futuro por corretora',
            'show me the order book depth for AAPL',
            'what is the bid ask spread right now',
            'top of book on the mini index',
            'muéstrame el libro de órdenes de PETR4',
            'cuánta profundidad hay en la punta compradora',
        ],
        keywords: ['book de ofertas', 'profundidade', 'DOM', 'bid ask', 'spread', 'nível 2', 'livro', 'ponta compradora', 'B3'],
        params: [
            { name: 'ativo', type: 'string', required: true, description: 'Ticker ou contrato cujo livro será exibido.' },
            { name: 'niveis', type: 'number', required: false, description: 'Quantos níveis de preço retornar em cada ponta.' },
            {
                name: 'agrupamento',
                type: 'enum',
                required: false,
                description: 'Como consolidar as ofertas exibidas.',
                enumValues: ['por_preco', 'por_corretora', 'por_ordem'],
            },
        ],
        confusableWith: ['trader.cotacao_ultimo_preco', 'trader.simular_ordem'],
    },
    {
        id: 'trader.posicao_pnl_dia',
        agent: 'trader',
        name: 'Ver posição e PnL do dia',
        description: 'Retorna a posição líquida atual por ativo junto do resultado aberto e realizado do dia marcado a mercado; use para saber o que está carregado em carteira e quanto se ganha ou perde agora.',
        utterances: [
            'quanto tô perdendo hoje?',
            'qual minha posição em dólar futuro agora?',
            'me dá o PnL do dia da mesa inteira',
            'tô comprado ou vendido em PETR4?',
            'quero o resultado aberto e o realizado separados',
            'posição líquida da carteira',
            'fechei no azul ou no vermelho até agora?',
            "what's my P&L today",
            'show my current net position in the mini index',
            'am I long or short on VALE3',
            'cuál es mi posición neta actual',
            'cuánto llevo ganado hoy en la cartera',
        ],
        keywords: ['PnL', 'P&L', 'MtM', 'marcação a mercado', 'posição líquida', 'resultado aberto', 'resultado realizado', 'exposição', 'B3'],
        params: [
            { name: 'ativo', type: 'string', required: false, description: 'Filtra por um ticker específico; vazio traz a carteira toda.' },
            {
                name: 'escopo',
                type: 'enum',
                required: false,
                description: 'Nível de agregação do resultado.',
                enumValues: ['trader', 'mesa', 'carteira_total'],
            },
            { name: 'moeda', type: 'enum', required: false, description: 'Moeda de apresentação do PnL.', enumValues: ['BRL', 'USD'] },
        ],
        confusableWith: ['trader.zerar_posicao', 'trader.historico_fills', 'trader.custo_execucao'],
    },
    {
        id: 'trader.custo_execucao',
        agent: 'trader',
        name: 'Analisar custo de execução',
        description: 'Calcula slippage e desvio do preço médio executado contra benchmarks VWAP, TWAP ou arrival price, somando corretagem e emolumentos; use para julgar a qualidade de execuções já ocorridas.',
        utterances: [
            'qual foi meu slippage na compra de PETR4 hoje?',
            'compara meu preço médio com o VWAP do dia',
            'roda o TCA daquela execução de VALE3',
            'quanto custou executar aquele bloco de 2 milhões?',
            'fiquei acima ou abaixo do TWAP naquela ordem?',
            'slippage médio da mesa na semana',
            'me abre os emolumentos e a corretagem dessa operação',
            'how much slippage did we pay on that block',
            'benchmark my fills against VWAP',
            'run a transaction cost analysis for yesterday',
            'cuánto fue el deslizamiento en esa ejecución',
            'compara mi precio medio contra el VWAP del día',
        ],
        keywords: ['TCA', 'slippage', 'VWAP', 'TWAP', 'arrival price', 'implementation shortfall', 'emolumentos', 'corretagem', 'B3'],
        params: [
            { name: 'ativo', type: 'string', required: false, description: 'Restringe a análise a um ticker ou contrato.' },
            {
                name: 'benchmark',
                type: 'enum',
                required: true,
                description: 'Referência de preço contra a qual medir o desvio.',
                enumValues: ['VWAP', 'TWAP', 'arrival_price', 'fechamento'],
            },
            {
                name: 'janela',
                type: 'enum',
                required: false,
                description: 'Período das execuções analisadas.',
                enumValues: ['hoje', 'ontem', 'semana', 'mes'],
            },
            { name: 'incluirTaxas', type: 'boolean', required: false, description: 'Se soma corretagem e emolumentos ao custo total.' },
        ],
        confusableWith: ['trader.historico_fills', 'trader.posicao_pnl_dia'],
    },
    {
        id: 'trader.rolar_futuro',
        agent: 'trader',
        name: 'Rolar contrato futuro',
        description: 'Executa a rolagem de posição em futuros do vencimento corrente para o seguinte, casando as duas pernas no spread de rolagem; use exclusivamente quando o assunto é troca de vencimento.',
        utterances: [
            'rola minha posição de WIN pro próximo vencimento',
            'faz a rolagem do DOL de agosto pra setembro',
            'quanto tá o spread de rolagem do índice?',
            'preciso rolar 300 contratos de DI1F27',
            'vira o vencimento do dólar futuro aí',
            'rolagem WDOQ26 para WDOU26',
            'meu contrato vence essa semana, joga pra frente',
            'roll my mini index futures to the next expiry',
            "what's the calendar spread on the roll",
            'roll 300 DI contracts forward',
            'rueda mi posición de futuros al siguiente vencimiento',
            'cuál es el spread de rolo del dólar',
        ],
        keywords: ['rolagem', 'calendar spread', 'vencimento', 'WDO', 'WIN', 'IND', 'DI1', 'contrato futuro', 'operação casada', 'B3'],
        params: [
            { name: 'contrato', type: 'string', required: true, description: 'Contrato de origem, ex.: WDOQ26 ou INDV26.' },
            { name: 'vencimentoDestino', type: 'string', required: false, description: 'Vencimento alvo; se omitido usa o vencimento imediatamente seguinte.' },
            { name: 'quantidade', type: 'number', required: false, description: 'Quantos contratos rolar; se omitido rola a posição inteira.' },
            {
                name: 'modo',
                type: 'enum',
                required: false,
                description: 'Como executar as duas pernas da rolagem.',
                enumValues: ['casada', 'pernas_separadas'],
            },
        ],
        confusableWith: ['trader.enviar_ordem', 'trader.zerar_posicao'],
    },
    {
        id: 'trader.zerar_posicao',
        agent: 'trader',
        name: 'Zerar ou reduzir posição',
        description: 'Encerra total ou parcialmente uma posição existente gerando automaticamente as ordens contrárias; use quando o pedido é sair ou diminuir exposição, não abrir posição nova nem consultar resultado.',
        utterances: [
            'zera minha posição em PETR4',
            'sai de tudo agora, sem pestanejar',
            'reduz pela metade a exposição em dólar',
            'quero liquidar 50% dos contratos de WIN',
            'me tira dessa posição, tá sangrando',
            'flat em tudo até o fechamento',
            'desmonta a comprada em VALE3 de forma passiva',
            'flatten my entire book right now',
            'cut half of my mini index exposure',
            'close out the long in ITUB4',
            'cierra toda mi posición en dólar futuro',
            'reduce mi exposición a la mitad',
        ],
        keywords: ['zerar', 'flatten', 'desmontar posição', 'reduzir exposição', 'close out', 'stop out', 'liquidar posição', 'B3'],
        params: [
            { name: 'ativo', type: 'string', required: false, description: 'Ativo a encerrar; vazio zera a carteira inteira.' },
            { name: 'percentual', type: 'number', required: false, description: 'Percentual da posição a encerrar, de 1 a 100.' },
            {
                name: 'tipoOrdem',
                type: 'enum',
                required: false,
                description: 'Como as ordens de saída serão executadas.',
                enumValues: ['mercado', 'limite', 'TWAP', 'VWAP'],
            },
            {
                name: 'urgencia',
                type: 'enum',
                required: false,
                description: 'Agressividade da saída.',
                enumValues: ['imediata', 'passiva', 'fim_do_dia'],
            },
        ],
        confusableWith: ['trader.enviar_ordem', 'trader.posicao_pnl_dia', 'trader.rolar_futuro'],
    },
    {
        id: 'trader.historico_fills',
        agent: 'trader',
        name: 'Listar execuções e fills',
        description: 'Lista os negócios já executados com horário, quantidade, preço, parciais e contraparte; use quando o usuário quer o extrato do que foi efetivamente negociado, não ordens ainda abertas nem posição consolidada.',
        utterances: [
            'me lista todos os fills de hoje',
            'quais negócios saíram em VALE3 essa manhã?',
            'extrato de execuções da semana passada',
            'que horas executou aquela ordem de ITUB4?',
            'quantos parciais teve naquela boleta grande?',
            'puxa o histórico de negócios da conta 12345',
            'me mostra os trades que fecharam ontem depois das 15h',
            'list every fill executed today',
            'show the trade history for last week',
            'when exactly did that order get filled',
            'muéstrame el historial de ejecuciones',
            'qué operaciones se cerraron ayer',
        ],
        keywords: ['fills', 'parciais', 'trade history', 'nota de corretagem', 'timestamp', 'contraparte', 'extrato de negócios', 'B3'],
        params: [
            { name: 'ativo', type: 'string', required: false, description: 'Filtra as execuções por ticker ou contrato.' },
            {
                name: 'periodo',
                type: 'enum',
                required: true,
                description: 'Janela de tempo das execuções listadas.',
                enumValues: ['hoje', 'ontem', 'semana', 'mes', 'customizado'],
            },
            { name: 'dataInicio', type: 'date', required: false, description: 'Início da janela quando o período for customizado.' },
            { name: 'dataFim', type: 'date', required: false, description: 'Fim da janela quando o período for customizado.' },
            { name: 'contaId', type: 'string', required: false, description: 'Conta ou carteira cujos negócios serão listados.' },
        ],
        confusableWith: ['trader.custo_execucao', 'trader.posicao_pnl_dia', 'trader.cancelar_alterar_ordem'],
    },
    {
        id: 'trader.cotacao_ultimo_preco',
        agent: 'trader',
        name: 'Consultar cotação',
        description: 'Devolve último preço negociado, variação, máxima, mínima e volume de um ativo na B3 ou no exterior; use para pergunta direta de preço, sem detalhar as ofertas do livro.',
        utterances: [
            'quanto tá PETR4?',
            'preço do dólar futuro agora',
            'a VALE3 subiu ou caiu hoje?',
            'qual a máxima e a mínima do Ibovespa hoje?',
            'cota aí o BOVA11 pra mim',
            'me dá o último negócio de MGLU3',
            'variação percentual do WIN desde a abertura',
            "what's AAPL trading at",
            'give me the last price on the mini index',
            'how much is the Ibovespa up today',
            'a cuánto está cotizando PETR4',
            'cuál fue el último precio del dólar',
        ],
        keywords: ['cotação', 'último preço', 'last', 'variação', 'máxima', 'mínima', 'volume financeiro', 'ticker', 'B3', 'fechamento anterior'],
        params: [
            { name: 'ativo', type: 'string', required: true, description: 'Ticker ou contrato a ser cotado.' },
            {
                name: 'campo',
                type: 'enum',
                required: false,
                description: 'Qual medida de preço retornar.',
                enumValues: ['ultimo', 'abertura', 'maxima', 'minima', 'fechamento_anterior', 'volume'],
            },
            { name: 'mercado', type: 'enum', required: false, description: 'Praça de negociação consultada.', enumValues: ['B3', 'exterior'] },
        ],
        confusableWith: ['trader.consultar_book'],
    },
    {
        id: 'trader.aluguel_ativos',
        agent: 'trader',
        name: 'Consultar aluguel de ativos',
        description: 'Consulta disponibilidade e taxas de empréstimo de ações no BTC e monta operações como doador ou tomador; use quando o tema é aluguel de papel para venda descoberta, nunca uma ordem comum de bolsa.',
        utterances: [
            'tem papel disponível pra alugar em MGLU3?',
            'qual a taxa do BTC de PETR4 hoje?',
            'quero tomar 100 mil ações de VALE3 emprestadas',
            'quanto tá custando o aluguel pra shortear AZUL4?',
            'sou doador, quanto recebo emprestando ITUB4?',
            'taxa doadora e tomadora de BOVA11',
            'preciso de papel pra vender descoberto amanhã cedo',
            "what's the borrow rate for shorting this name",
            'is there any inventory available to borrow',
            'I want to lend out my ITUB4 shares',
            'cuál es la tasa de préstamo de acciones',
            'hay disponibilidad para tomar prestado VALE3',
        ],
        keywords: ['BTC', 'banco de títulos', 'aluguel de ações', 'doador', 'tomador', 'taxa de aluguel', 'venda descoberta', 'short', 'B3', 'CBLC'],
        params: [
            { name: 'ativo', type: 'string', required: true, description: 'Ticker do papel a ser alugado ou doado.' },
            { name: 'papel', type: 'enum', required: true, description: 'Lado da operação de empréstimo.', enumValues: ['doador', 'tomador'] },
            { name: 'quantidade', type: 'number', required: false, description: 'Quantidade de ações do contrato de aluguel.' },
            { name: 'prazoDias', type: 'number', required: false, description: 'Prazo do empréstimo em dias corridos.' },
            { name: 'taxaMaxima', type: 'number', required: false, description: 'Taxa anual máxima aceita pelo tomador, em percentual.' },
        ],
        confusableWith: ['trader.enviar_ordem'],
    },
    {
        id: 'trader.simular_ordem',
        agent: 'trader',
        name: 'Simular ordem',
        description: 'Estima preço médio, impacto de mercado, margem exigida e custos de uma ordem hipotética sem enviá-la; use para análise pré-trade e what-if, jamais para executar de verdade.',
        utterances: [
            'simula aí a compra de 1 milhão de PETR4 antes de mandar',
            'se eu vender 500 contratos de WIN, qual o impacto no preço?',
            'quanto de margem vai travar se eu montar essa posição?',
            'faz um what-if dessa ordem antes de boletar',
            'qual seria o preço médio se eu varrer as pontas agora?',
            'pré-trade de 2 mil DOLFUT',
            'roda a simulação primeiro, não manda nada ainda',
            'simulate this order without sending it',
            'what would the market impact of that size be',
            'dry run this trade before we go live',
            'simula esta orden antes de enviarla',
            'cuál sería el impacto de mercado de esa operación',
        ],
        keywords: ['pré-trade', 'what-if', 'simulação', 'impacto de mercado', 'margem requerida', 'dry run', 'preço médio estimado', 'B3'],
        params: [
            { name: 'ativo', type: 'string', required: true, description: 'Ticker ou contrato da ordem hipotética.' },
            { name: 'lado', type: 'enum', required: true, description: 'Direção simulada.', enumValues: ['compra', 'venda'] },
            { name: 'quantidade', type: 'number', required: true, description: 'Quantidade hipotética em ações ou contratos.' },
            {
                name: 'estrategia',
                type: 'enum',
                required: false,
                description: 'Estratégia de execução assumida na simulação.',
                enumValues: ['mercado', 'limite', 'TWAP', 'VWAP', 'iceberg'],
            },
            { name: 'preco', type: 'number', required: false, description: 'Preço limite assumido, quando a estratégia exigir.' },
        ],
        confusableWith: ['trader.enviar_ordem', 'trader.consultar_book', 'trader.custo_execucao'],
    },
    {
        id: 'trader.status_roteamento',
        agent: 'trader',
        name: 'Checar conectividade e roteamento',
        description: 'Verifica saúde das sessões FIX, latência e disponibilidade dos destinos de roteamento de ordens; use quando a dúvida é de infraestrutura ou as ordens não estão chegando ao mercado.',
        utterances: [
            'a sessão FIX tá de pé?',
            'as ordens não estão chegando na bolsa, o que houve?',
            'status do roteamento pro exterior',
            'qual a latência atual pro DMA da B3?',
            'caiu a conexão com a corretora?',
            'checa se o gateway de ordens tá saudável antes da abertura',
            'heartbeat travou, dá uma olhada aí',
            'is the FIX session up',
            'check order routing connectivity status',
            'what is our current latency to the exchange',
            'está activa la conexión con el mercado',
            'revisa el estado del enrutamiento de órdenes',
        ],
        keywords: ['FIX', 'sessão', 'DMA', 'gateway', 'latência', 'roteamento', 'heartbeat', 'colocation', 'B3', 'order gateway'],
        params: [
            {
                name: 'destino',
                type: 'enum',
                required: false,
                description: 'Qual rota verificar.',
                enumValues: ['B3', 'exterior', 'todos'],
            },
            {
                name: 'detalhe',
                type: 'enum',
                required: false,
                description: 'Profundidade do diagnóstico retornado.',
                enumValues: ['resumo', 'completo'],
            },
        ],
    },
];
//# sourceMappingURL=trader.js.map