import type { AgentDef, CommandDef } from '../types.js';

export const contentAgent: AgentDef = {
  id: 'content',
  name: 'Conteúdo',
  description:
    'Produção editorial da casa de research: redação de relatórios e teses, resumo de calls de resultados, newsletters e cartas ao investidor, posts para redes sociais, roteiros de vídeo e podcast, títulos e chamadas, revisão de compliance e disclaimers, tradução, extração de destaques de documentos longos, gráficos e artes de apoio, busca no acervo publicado e agendamento/publicação nos canais.',
};

// `confusableWith` só alimenta a matriz de confusão do eval; por isso aponta
// apenas para ids deste agente, cuja existência é garantida por este arquivo.
export const contentCommands: CommandDef[] = [
  {
    id: 'content.redigir_relatorio',
    agent: 'content',
    name: 'Redigir relatório de análise',
    description:
      'Redige do zero um relatório de análise ou tese de investimento sobre um ativo ou setor, com recomendação, valuation e preço-alvo; use quando a entrega é o documento de research completo, não um resumo, uma newsletter ou uma peça curta.',
    utterances: [
      'escreve o relatório de PETR4 com recomendação e preço-alvo',
      'monta a tese de investimento pra Vale, umas dez páginas',
      'initiation coverage de RENT3',
      'preciso de um report completo do setor bancário pra sair amanhã cedo',
      'redigir análise fundamentalista de WEGE3 com valuation por DCF',
      'relatório setorial novo',
      'faz aquele texto de research da Suzano detalhando upside e riscos',
      'write a full equity research report on Itaú with a price target',
      'draft the investment thesis for the mining sector',
      'new initiation report, sell-side format',
      'redacta el informe de análisis de Bimbo con precio objetivo',
      'necesito una tesis de inversión completa del sector eléctrico',
    ],
    keywords: [
      'CNPI',
      'preço-alvo',
      'target price',
      'initiation coverage',
      'DCF',
      'valuation',
      'sell-side',
      'tese de investimento',
      'upside',
      'RCVM 20',
    ],
    params: [
      {
        name: 'ativo',
        type: 'string',
        required: true,
        description: 'Ticker, empresa ou setor que é objeto do relatório. Ex.: "PETR4", "setor elétrico".',
      },
      {
        name: 'tipo_relatorio',
        type: 'enum',
        required: false,
        description: 'Formato editorial da peça de research.',
        enumValues: ['initiation', 'update', 'flash', 'setorial', 'tematico'],
      },
      {
        name: 'recomendacao',
        type: 'enum',
        required: false,
        description: 'Recomendação a ser sustentada no texto.',
        enumValues: ['compra', 'neutro', 'venda', 'em_revisao'],
      },
      {
        name: 'extensao',
        type: 'enum',
        required: false,
        description: 'Tamanho alvo do documento.',
        enumValues: ['curto', 'medio', 'longo'],
      },
      {
        name: 'publico',
        type: 'enum',
        required: false,
        description: 'Público leitor, que define profundidade técnica e jargão.',
        enumValues: ['varejo', 'institucional', 'private'],
      },
    ],
    confusableWith: [
      'content.montar_newsletter',
      'content.resumir_call_resultados',
      'content.extrair_destaques',
    ],
  },

  {
    id: 'content.resumir_call_resultados',
    agent: 'content',
    name: 'Resumir call de resultados',
    description:
      'Resume a teleconferência de resultados de uma empresa a partir da transcrição ou do áudio, destacando guidance, tom da gestão e Q&A com analistas; use quando a fonte é o evento de earnings de um trimestre, não um documento escrito qualquer.',
    utterances: [
      'resume a call de resultados da Vale do 3T25',
      'o que o CFO falou de guidance na teleconferência?',
      'TL;DR da earnings call de PETR4',
      'resumo do Q&A com os analistas na call de ontem',
      'call do Itaú, pontos principais',
      'me passa o que saiu de relevante na teleconferência da Ambev, principalmente margem',
      'condensa a transcrição da conference call do 2T em meia página',
      'summarize the Q3 earnings call for Petrobras',
      'what did management say about guidance on the call?',
      'earnings call recap, include the analyst Q&A',
      'resume la llamada de resultados del tercer trimestre',
      'qué dijo la gerencia en la teleconferencia sobre el guidance',
    ],
    keywords: [
      'earnings call',
      'teleconferência',
      'guidance',
      'Q&A',
      '3T25',
      'transcrição',
      'CFO',
      'release trimestral',
      'conference call',
    ],
    params: [
      {
        name: 'empresa',
        type: 'string',
        required: true,
        description: 'Empresa ou ticker cuja call de resultados será resumida.',
      },
      {
        name: 'trimestre',
        type: 'enum',
        required: false,
        description: 'Trimestre de referência do evento.',
        enumValues: ['1T', '2T', '3T', '4T'],
      },
      {
        name: 'ano',
        type: 'number',
        required: false,
        description: 'Ano de referência do trimestre. Ex.: 2025.',
      },
      {
        name: 'foco',
        type: 'enum',
        required: false,
        description: 'Recorte que deve dominar o resumo.',
        enumValues: ['guidance', 'q_and_a', 'numeros', 'estrategia', 'tudo'],
      },
      {
        name: 'formato_saida',
        type: 'enum',
        required: false,
        description: 'Como o resumo deve ser entregue.',
        enumValues: ['bullets', 'texto_corrido', 'nota_curta'],
      },
    ],
    confusableWith: ['content.extrair_destaques', 'content.redigir_relatorio'],
  },

  {
    id: 'content.gerar_post_social',
    agent: 'content',
    name: 'Gerar post para redes sociais',
    description:
      'Cria o texto de um post para LinkedIn, X, Instagram ou TikTok a partir de um tema ou de uma peça existente, já no tom e no limite de caracteres da plataforma; use para publicação social, não para newsletter, título isolado ou roteiro falado.',
    utterances: [
      'faz um post pro LinkedIn sobre a alta do dólar',
      'thread no X explicando o corte da Selic',
      'carrossel de Instagram com cinco slides sobre renda fixa',
      'reescreve isso em tom mais leve pro LinkedIn, sem cara de relatório',
      'tweet curto',
      'transforma esse trecho do relatório num post pro nosso perfil',
      'legenda pro reels do analista falando sobre o IPO da semana',
      'write a LinkedIn post about the Fed decision',
      'turn this into a Twitter thread, six tweets max',
      'short caption for Instagram, casual tone',
      'arma un post de LinkedIn sobre la subida de tasas',
      'un hilo de X explicando la inflación de junio',
    ],
    keywords: [
      'LinkedIn',
      'thread',
      'carrossel',
      'Instagram',
      'reels',
      'hashtag',
      'copy',
      'engajamento',
      'X/Twitter',
    ],
    params: [
      {
        name: 'plataforma',
        type: 'enum',
        required: true,
        description: 'Rede social de destino, que define limite de caracteres e formato.',
        enumValues: ['linkedin', 'x', 'instagram', 'tiktok', 'youtube_shorts', 'threads'],
      },
      {
        name: 'tema',
        type: 'string',
        required: true,
        description: 'Assunto do post ou trecho da peça de origem a ser adaptado.',
      },
      {
        name: 'formato',
        type: 'enum',
        required: false,
        description: 'Estrutura do post na plataforma.',
        enumValues: ['texto_unico', 'thread', 'carrossel', 'legenda_video'],
      },
      {
        name: 'tom',
        type: 'enum',
        required: false,
        description: 'Registro de linguagem do post.',
        enumValues: ['tecnico', 'didatico', 'provocativo', 'institucional'],
      },
      {
        name: 'incluir_hashtags',
        type: 'boolean',
        required: false,
        description: 'Se deve sugerir hashtags ao final do post.',
      },
    ],
    confusableWith: [
      'content.criar_titulo_chamada',
      'content.montar_newsletter',
      'content.agendar_publicacao',
    ],
  },

  {
    id: 'content.montar_newsletter',
    agent: 'content',
    name: 'Montar newsletter',
    description:
      'Empacota research, notícias e destaques do período numa edição de newsletter ou carta ao investidor, com seções na ordem editorial da casa; use quando a entrega é o e-mail recorrente enviado à base de assinantes.',
    utterances: [
      'monta a newsletter desta semana com os três relatórios que saíram',
      'carta ao investidor de julho, formato de sempre',
      'edição de amanhã do daily',
      'transforma esse research em e-mail pra base de assinantes',
      'newsletter quinzenal com bloco de macro, cripto e renda variável',
      'preciso fechar a edição 142 até as 18h, puxa os destaques da semana',
      'boletim semanal pros clientes private',
      "put together this week's investor newsletter",
      'draft the monthly letter to subscribers with three sections',
      'turn these research pieces into an email edition',
      'arma el newsletter semanal para los suscriptores',
      'carta mensual al inversor con las secciones de siempre',
    ],
    keywords: [
      'newsletter',
      'carta ao investidor',
      'daily',
      'edição',
      'assinantes',
      'e-mail marketing',
      'open rate',
      'boletim',
    ],
    params: [
      {
        name: 'periodicidade',
        type: 'enum',
        required: true,
        description: 'Cadência da edição a ser montada.',
        enumValues: ['diaria', 'semanal', 'quinzenal', 'mensal'],
      },
      {
        name: 'secoes',
        type: 'string',
        required: false,
        description: 'Seções desejadas, em ordem. Ex.: "macro, renda variável, cripto".',
      },
      {
        name: 'fontes',
        type: 'string',
        required: false,
        description: 'Peças, relatórios ou links que devem alimentar a edição.',
      },
      {
        name: 'publico',
        type: 'enum',
        required: false,
        description: 'Base que receberá o envio.',
        enumValues: ['varejo', 'private', 'institucional', 'geral'],
      },
      {
        name: 'data_envio',
        type: 'date',
        required: false,
        description: 'Data prevista de envio da edição.',
      },
    ],
    confusableWith: [
      'content.redigir_relatorio',
      'content.gerar_post_social',
      'content.agendar_publicacao',
    ],
  },

  {
    id: 'content.revisar_compliance',
    agent: 'content',
    name: 'Revisar para compliance',
    description:
      'Revisa uma peça já escrita contra as regras do regulador e da área de compliance, apontando trechos irregulares e inserindo disclaimers e selo CNPI; use quando o texto existe e precisa passar pelo crivo regulatório antes de sair.',
    utterances: [
      'passa esse relatório no compliance antes de publicar',
      'faltou disclaimer nesse texto?',
      'revisão CNPI',
      'esse post promete rentabilidade, tá irregular pela CVM?',
      'ajusta a linguagem pra não configurar recomendação personalizada',
      'checa se o material tá aderente à RCVM 20 e coloca as ressalvas de praxe',
      'compliance aprovou? se não, me diz o que precisa mudar no texto',
      'run this piece through compliance review',
      'add the mandatory disclaimers and risk warnings',
      'is this copy compliant with the analyst regulation?',
      'revisa el texto para cumplimiento normativo',
      'agrega el descargo de responsabilidad obligatorio',
    ],
    keywords: [
      'CNPI',
      'RCVM 20',
      'CVM',
      'disclaimer',
      'APIMEC',
      'compliance',
      'suitability',
      'conflito de interesse',
      'ANBIMA',
      'ressalva',
    ],
    params: [
      {
        name: 'texto',
        type: 'string',
        required: true,
        description: 'Conteúdo ou identificador da peça que será revisada.',
      },
      {
        name: 'canal',
        type: 'enum',
        required: false,
        description: 'Canal de veiculação, que muda as exigências aplicáveis.',
        enumValues: ['relatorio', 'redes_sociais', 'video', 'newsletter', 'site'],
      },
      {
        name: 'nivel_revisao',
        type: 'enum',
        required: false,
        description: 'Rigor da revisão a ser aplicada.',
        enumValues: ['leve', 'padrao', 'rigoroso'],
      },
      {
        name: 'jurisdicao',
        type: 'enum',
        required: false,
        description: 'Regime regulatório de referência.',
        enumValues: ['BR', 'US', 'EU'],
      },
      {
        name: 'inserir_disclaimer',
        type: 'boolean',
        required: false,
        description: 'Se os disclaimers padrão devem ser inseridos direto na peça.',
      },
    ],
    confusableWith: ['content.traduzir_conteudo', 'content.agendar_publicacao'],
  },

  {
    id: 'content.traduzir_conteudo',
    agent: 'content',
    name: 'Traduzir conteúdo',
    description:
      'Traduz ou localiza uma peça já pronta para outro idioma, preservando jargão financeiro, tickers e formatação; use quando o conteúdo existe e a única mudança pedida é de idioma.',
    utterances: [
      'traduz esse relatório pro inglês mantendo os termos técnicos',
      'versão em espanhol da newsletter',
      'verte pro português o report que o banco lá fora publicou',
      'traduzir pra en-US',
      'esse material vai pro investidor estrangeiro, precisa sair em inglês',
      'faz a tradução do post mas não traduz os tickers nem "preço-alvo"',
      'localiza esse texto pro público do México',
      'translate this report into Spanish',
      'I need an English version of the weekly letter',
      'localize the deck copy for LatAm readers',
      'traduce el informe al portugués',
      'necesito esta pieza en inglés, con la jerga financiera intacta',
    ],
    keywords: [
      'tradução',
      'en-US',
      'pt-BR',
      'es-LATAM',
      'localização',
      'glossário',
      'bilíngue',
      'versão em inglês',
    ],
    params: [
      {
        name: 'texto',
        type: 'string',
        required: true,
        description: 'Conteúdo ou identificador da peça a ser traduzida.',
      },
      {
        name: 'idioma_destino',
        type: 'enum',
        required: true,
        description: 'Idioma para o qual a peça será traduzida.',
        enumValues: ['en', 'es', 'pt', 'fr', 'zh'],
      },
      {
        name: 'idioma_origem',
        type: 'enum',
        required: false,
        description: 'Idioma original da peça; "auto" deixa a detecção por conta do sistema.',
        enumValues: ['pt', 'en', 'es', 'auto'],
      },
      {
        name: 'registro',
        type: 'enum',
        required: false,
        description: 'Registro de linguagem da tradução.',
        enumValues: ['formal', 'coloquial', 'tecnico'],
      },
      {
        name: 'preservar_termos',
        type: 'boolean',
        required: false,
        description: 'Se tickers, siglas e termos de mercado devem ficar no idioma original.',
      },
    ],
    confusableWith: ['content.revisar_compliance', 'content.redigir_relatorio'],
  },

  {
    id: 'content.gerar_roteiro_audiovisual',
    agent: 'content',
    name: 'Gerar roteiro de vídeo ou podcast',
    description:
      'Escreve roteiro falado para vídeo, live, webinar ou podcast, com blocos, marcações de tempo e deixas de entrada de imagem; use quando a saída é um texto para ser lido em voz alta diante de câmera ou microfone.',
    utterances: [
      'roteiro do vídeo de cinco minutos sobre a temporada de balanços',
      'escreve o script do podcast desta semana com blocos e tempos',
      'pauta e roteiro da live de abertura de mercado',
      'roteiro pro Shorts',
      'preciso do texto que o analista vai ler no teleprompter amanhã cedo',
      'estrutura o episódio: abertura, dois blocos de entrevista e encerramento',
      'monta o roteiro do vídeo com deixa pra entrar o gráfico na tela',
      'write a ten-minute video script on the rate decision',
      'podcast outline with segments and timestamps',
      'teleprompter script for the market open show',
      'escribe el guion del podcast de esta semana',
      'necesito un guion de video de tres minutos sobre el IPO',
    ],
    keywords: [
      'roteiro',
      'script',
      'podcast',
      'teleprompter',
      'live',
      'Shorts',
      'episódio',
      'deixa',
      'pauta',
      'timestamps',
    ],
    params: [
      {
        name: 'formato',
        type: 'enum',
        required: true,
        description: 'Tipo de peça audiovisual a ser roteirizada.',
        enumValues: ['video_longo', 'video_curto', 'podcast', 'live', 'webinar'],
      },
      {
        name: 'tema',
        type: 'string',
        required: true,
        description: 'Assunto do episódio ou vídeo.',
      },
      {
        name: 'duracao_minutos',
        type: 'number',
        required: false,
        description: 'Duração alvo em minutos, usada para dimensionar os blocos.',
      },
      {
        name: 'num_blocos',
        type: 'number',
        required: false,
        description: 'Quantidade de blocos ou segmentos do roteiro.',
      },
      {
        name: 'tom',
        type: 'enum',
        required: false,
        description: 'Tom da narração.',
        enumValues: ['didatico', 'jornalistico', 'informal', 'institucional'],
      },
    ],
    confusableWith: ['content.gerar_post_social', 'content.redigir_relatorio'],
  },

  {
    id: 'content.extrair_destaques',
    agent: 'content',
    name: 'Extrair destaques de documento',
    description:
      'Varre um documento longo de terceiros — prospecto, fato relevante, ata, formulário de referência, contrato — e devolve os pontos que importam com a página de origem; use quando existe um arquivo extenso a garimpar, e não uma teleconferência de resultados.',
    utterances: [
      'puxa os destaques desse prospecto de 300 páginas',
      'o que tem de relevante nesse fato relevante divulgado na B3?',
      'highlights do PDF',
      'lê a ata do Copom e me diz os trechos que mudaram de tom',
      'extrai os números principais do formulário de referência com a página de cada um',
      'marca os pontos críticos do contrato pra eu não ler as oitenta folhas',
      'lista em bullets os fatores de risco desse documento anexo',
      'pull the key points out of this 200-page prospectus',
      'extract the highlights from the attached PDF with page references',
      'what actually matters in this material fact filing?',
      'extrae los puntos destacados del prospecto',
      'dime lo relevante de este documento largo, con las páginas',
    ],
    keywords: [
      'prospecto',
      'fato relevante',
      'formulário de referência',
      'ata do Copom',
      'PDF',
      'highlights',
      'fatores de risco',
      'B3',
      'edital',
    ],
    params: [
      {
        name: 'documento',
        type: 'string',
        required: true,
        description: 'Caminho, link ou identificador do documento a ser processado.',
      },
      {
        name: 'tipo_documento',
        type: 'enum',
        required: false,
        description: 'Natureza do documento, que orienta o que buscar.',
        enumValues: [
          'prospecto',
          'fato_relevante',
          'ata',
          'formulario_referencia',
          'contrato',
          'apresentacao',
          'outro',
        ],
      },
      {
        name: 'foco',
        type: 'string',
        required: false,
        description: 'Tema ou seção que deve concentrar a extração. Ex.: "fatores de risco".',
      },
      {
        name: 'max_destaques',
        type: 'number',
        required: false,
        description: 'Número máximo de destaques a retornar.',
      },
      {
        name: 'incluir_referencia_pagina',
        type: 'boolean',
        required: false,
        description: 'Se cada destaque deve vir com a página de origem.',
      },
    ],
    confusableWith: ['content.resumir_call_resultados', 'content.buscar_acervo'],
  },

  {
    id: 'content.criar_titulo_chamada',
    agent: 'content',
    name: 'Criar título e chamada',
    description:
      'Gera opções de título, subtítulo, linha fina ou assunto de e-mail para uma peça que já está escrita, otimizando clareza e abertura; use quando só falta a manchete e o corpo do texto já existe.',
    utterances: [
      'me dá cinco opções de título pra esse relatório',
      'essa manchete tá fraca, melhora',
      'chamada e linha fina',
      'qual assunto de e-mail teria mais abertura pra essa newsletter?',
      'cria um subtítulo que explique o gancho sem entregar tudo',
      'título com no máximo 60 caracteres, e sem clickbait',
      'sugere uma headline pro post e uma frase de apoio embaixo',
      'give me ten headline options for this piece',
      'write a better subject line for the newsletter',
      'punchier title, under 60 characters',
      'dame cinco títulos alternativos para este informe',
      'necesito un antetítulo y una bajada para la nota',
    ],
    keywords: [
      'headline',
      'manchete',
      'subject line',
      'linha fina',
      'chamada',
      'subtítulo',
      'CTR',
      'clickbait',
      'SEO',
    ],
    params: [
      {
        name: 'texto_base',
        type: 'string',
        required: true,
        description: 'Peça já escrita a partir da qual os títulos serão criados.',
      },
      {
        name: 'canal',
        type: 'enum',
        required: false,
        description: 'Onde o título será usado, o que define tamanho e estilo.',
        enumValues: ['relatorio', 'newsletter', 'site', 'redes_sociais', 'video'],
      },
      {
        name: 'quantidade',
        type: 'number',
        required: false,
        description: 'Quantas opções de título devem ser geradas.',
      },
      {
        name: 'limite_caracteres',
        type: 'number',
        required: false,
        description: 'Teto de caracteres por título.',
      },
      {
        name: 'estilo',
        type: 'enum',
        required: false,
        description: 'Estilo editorial do título.',
        enumValues: ['informativo', 'provocativo', 'seo', 'sobrio'],
      },
    ],
    confusableWith: ['content.gerar_post_social', 'content.montar_newsletter'],
  },

  {
    id: 'content.agendar_publicacao',
    agent: 'content',
    name: 'Agendar publicação',
    description:
      'Programa data, hora e canal de saída de uma peça já aprovada, publica na hora ou tira do ar o que já foi publicado; use quando a decisão é sobre quando e onde o conteúdo sai, e não sobre escrevê-lo.',
    utterances: [
      'agenda esse post pro LinkedIn às 9h de terça',
      'publica agora no site',
      'programa o disparo da newsletter pra quinta às 7 da manhã',
      'joga isso na fila do calendário editorial de agosto',
      'tira do ar aquele post de ontem',
      'reagenda o vídeo pra depois do fechamento do pregão',
      'sobe pro CMS mas deixa como rascunho até o compliance liberar',
      'schedule this post for Tuesday at 9am',
      'publish it to the site right now',
      'push the newsletter send to Thursday morning',
      'programa la publicación para el lunes a las ocho',
      'súbelo ahora mismo al sitio',
    ],
    keywords: [
      'agendar',
      'publicar',
      'CMS',
      'calendário editorial',
      'disparo',
      'rascunho',
      'despublicar',
      'fuso',
      'pregão',
    ],
    params: [
      {
        name: 'peca_id',
        type: 'string',
        required: true,
        description: 'Identificador ou título da peça já aprovada que será publicada.',
      },
      {
        name: 'canal',
        type: 'enum',
        required: true,
        description: 'Canal de veiculação da peça.',
        enumValues: ['site', 'linkedin', 'x', 'instagram', 'youtube', 'email', 'app'],
      },
      {
        name: 'acao',
        type: 'enum',
        required: false,
        description: 'Operação a executar sobre a publicação.',
        enumValues: ['agendar', 'publicar_agora', 'despublicar', 'reagendar'],
      },
      {
        name: 'data_hora',
        type: 'date',
        required: false,
        description: 'Data e hora de saída, no fuso de Brasília.',
      },
      {
        name: 'status',
        type: 'enum',
        required: false,
        description: 'Estado em que a peça deve ficar no CMS.',
        enumValues: ['rascunho', 'revisao', 'aprovado'],
      },
    ],
    confusableWith: ['content.montar_newsletter', 'content.gerar_post_social'],
  },

  {
    id: 'content.buscar_acervo',
    agent: 'content',
    name: 'Buscar no acervo publicado',
    description:
      'Procura no acervo da casa o que já foi publicado sobre um tema, ativo ou período e devolve as peças com link e data; use quando o conteúdo já existe em algum lugar e o pedido é encontrá-lo ou reaproveitá-lo.',
    utterances: [
      'a gente já escreveu alguma coisa sobre Vale esse ano?',
      'acha o relatório antigo do IPO da Raízen',
      'busca no acervo',
      'quantas vezes falamos de Selic na newsletter em 2025?',
      'me manda o link daquele post que bombou sobre renda fixa',
      'procura nos arquivos tudo que publicamos de setor elétrico desde janeiro',
      'tem material nosso sobre debênture incentivada pra reaproveitar?',
      'search our archive for anything we published on Petrobras',
      'did we cover the Fed decision last month?',
      'find that old report about the IPO',
      'busca en el archivo lo que publicamos sobre Vale',
      '¿ya escribimos algo del sector eléctrico?',
    ],
    keywords: [
      'acervo',
      'arquivo',
      'já publicado',
      'histórico',
      'link',
      'republicar',
      'biblioteca',
      'tag',
    ],
    params: [
      {
        name: 'termo',
        type: 'string',
        required: true,
        description: 'Tema, ticker ou palavra-chave a procurar no acervo.',
      },
      {
        name: 'periodo',
        type: 'enum',
        required: false,
        description: 'Janela temporal da busca.',
        enumValues: ['ultimos_7_dias', 'ultimos_30_dias', 'ultimo_trimestre', 'ultimo_ano', 'tudo'],
      },
      {
        name: 'canal',
        type: 'enum',
        required: false,
        description: 'Restringe a busca a um tipo de peça.',
        enumValues: ['relatorio', 'newsletter', 'redes_sociais', 'video', 'site', 'todos'],
      },
      {
        name: 'autor',
        type: 'string',
        required: false,
        description: 'Analista ou redator responsável pela peça.',
      },
      {
        name: 'limite',
        type: 'number',
        required: false,
        description: 'Número máximo de resultados a retornar.',
      },
    ],
    confusableWith: ['content.extrair_destaques', 'content.agendar_publicacao'],
  },

  {
    id: 'content.gerar_visual_apoio',
    agent: 'content',
    name: 'Gerar visual de apoio',
    description:
      'Produz o gráfico, card, infográfico ou capa que acompanha uma peça, a partir de uma série de dados ou de uma tabela, já no template e proporção do canal; use quando o pedido é a imagem, não o texto.',
    utterances: [
      'faz um gráfico de barras do lucro trimestral pra entrar no relatório',
      'card visual com os três números principais',
      'infográfico do fluxo da oferta',
      'monta a arte do post com a cotação do dólar no ano',
      'preciso de uma imagem de capa pro vídeo, em 16:9',
      'plota a série do IPCA dos últimos 24 meses no nosso template',
      'transforma essa tabela num visual que caiba no story',
      'create a bar chart of quarterly revenue for the report',
      'design a cover image for the video, 16:9',
      'make an infographic out of this table',
      'haz un gráfico de líneas con la serie del dólar',
      'necesito una imagen de portada para el informe',
    ],
    keywords: [
      'gráfico',
      'infográfico',
      'card',
      'capa',
      'template',
      '16:9',
      'story',
      'arte',
      'IPCA',
    ],
    params: [
      {
        name: 'dados',
        type: 'string',
        required: true,
        description: 'Série, tabela ou trecho da peça que alimenta o visual.',
      },
      {
        name: 'tipo_visual',
        type: 'enum',
        required: true,
        description: 'Tipo de peça gráfica a ser gerada.',
        enumValues: ['linha', 'barra', 'pizza', 'area', 'tabela', 'card', 'infografico', 'capa'],
      },
      {
        name: 'formato',
        type: 'enum',
        required: false,
        description: 'Proporção da imagem, conforme o canal de destino.',
        enumValues: ['16:9', '1:1', '9:16', '4:5'],
      },
      {
        name: 'paleta',
        type: 'enum',
        required: false,
        description: 'Paleta de cores do template da casa.',
        enumValues: ['institucional', 'alto_contraste', 'monocromatica'],
      },
      {
        name: 'titulo_visual',
        type: 'string',
        required: false,
        description: 'Título a estampar no gráfico ou card.',
      },
    ],
    confusableWith: ['content.gerar_post_social', 'content.extrair_destaques'],
  },
];
